namespace AccessControlService.Infrastructure.Persistence;

/// <summary>
/// A single active Full-profile-access grant: one row per current holder. Deliberately not a
/// soft-delete table -- when a grant is revoked the row is removed; <see cref="FullProfileAccessJournalEntry"/>
/// is the durable, append-only log of every grant and revoke action.
/// </summary>
public sealed class FullProfileAccessGrant
{
    /// <summary>Surrogate primary key, generated by the application (not the database).</summary>
    public Guid Id { get; set; }

    /// <summary>The person who currently holds Full-profile-access.</summary>
    public Guid HolderId { get; set; }

    /// <summary>
    /// The person who created this grant. For the bootstrap seed row this is the same as
    /// <see cref="HolderId"/> (self-seeded at deployment). For subsequent grants this is the
    /// actor who called <c>POST /api/v1/full-profile-access/grant</c>.
    /// </summary>
    public Guid GrantedByActorId { get; set; }

    /// <summary>UTC timestamp at which this grant was created.</summary>
    public DateTime GrantedAtUtc { get; set; }
}
