namespace AccessControlService.Infrastructure.Persistence;

/// <summary>Action recorded in the Full-profile-access journal.</summary>
public enum FullProfileAccessAction
{
    Grant,
    Revoke,
}

/// <summary>
/// A single entry in the narrow journal for Full-profile-access changes (spec §3.4). One row per
/// grant or revoke action, written atomically with the corresponding <see cref="FullProfileAccessGrant"/>
/// row mutation. Append-only -- rows are never updated or deleted.
/// </summary>
public sealed class FullProfileAccessJournalEntry
{
    /// <summary>Surrogate primary key, generated by the application (not the database).</summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The person who performed the grant or revoke action. For the bootstrap seed row this is
    /// the same as <see cref="SubjectId"/> (self-seeded at deployment).
    /// </summary>
    public Guid ActorId { get; set; }

    /// <summary>
    /// The person whose Full-profile-access was granted or revoked by this action.
    /// </summary>
    public Guid SubjectId { get; set; }

    /// <summary>Whether this entry records a grant or a revoke.</summary>
    public FullProfileAccessAction Action { get; set; }

    /// <summary>UTC timestamp at which this action occurred.</summary>
    public DateTime OccurredAtUtc { get; set; }
}
