// <auto-generated />
using System;
using AccessControlService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControlService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260904180115_ConvertFullProfileAccessActionToString")]
    partial class ConvertFullProfileAccessActionToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Label = "Fixture Dept: Headquarters"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Label = "Fixture Dept: Engineering",
                            ParentDepartmentId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Dept: Platform",
                            ParentDepartmentId = new Guid("11111111-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.FullProfileAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HolderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HolderId")
                        .IsUnique();

                    b.ToTable("full_profile_access_grants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            GrantedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantedByActorId = new Guid("22222222-0000-0000-0000-000000000003"),
                            HolderId = new Guid("22222222-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.FullProfileAccessJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("full_profile_access_journal_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            Action = "Grant",
                            ActorId = new Guid("22222222-0000-0000-0000-000000000003"),
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubjectId = new Guid("22222222-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagesDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PeoplePartnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ManagesDepartmentId")
                        .IsUnique();

                    b.HasIndex("PeoplePartnerId");

                    b.ToTable("people", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Label = "Fixture Person: Executive",
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Label = "Fixture Person: Director",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000001"),
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Person: Platform Lead",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000002"),
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Person: Engineer",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000003"),
                            PeoplePartnerId = new Guid("22222222-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Label = "Fixture Person: Delivery Manager (Project Phoenix)"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Label = "Fixture Person: Project Manager (Project Phoenix)"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            Label = "Fixture Person: Project Assignee (Project Phoenix)"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            Label = "Fixture Person: Delivery Manager (Project Orion, unrelated to Phoenix)"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            Label = "Fixture Person: HR Director"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000a"),
                            Label = "Fixture Person: HR Partner (Engineer's assigned PP)",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.ProjectAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId", "PersonId")
                        .IsUnique();

                    b.ToTable("project_assignments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000005"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000001"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000006"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000001"),
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000007"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000001"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000008"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000002"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000003"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000002"),
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000006"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000004"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000002"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000007"),
                            PersonId = new Guid("22222222-0000-0000-0000-000000000003"),
                            ProjectId = new Guid("33333333-0000-0000-0000-000000000003"),
                            Role = 2
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.ProjectAssignmentEventWatermark", b =>
                {
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastAppliedEventId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastAppliedVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OwnedPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnedProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("AggregateId");

                    b.HasIndex("OwnedProjectId", "OwnedPersonId")
                        .IsUnique()
                        .HasFilter("\"OwnedProjectId\" IS NOT NULL AND \"OwnedPersonId\" IS NOT NULL");

                    b.ToTable("project_assignment_event_watermarks", (string)null);
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Department", b =>
                {
                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Person", b =>
                {
                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessControlService.Infrastructure.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("ManagesDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessControlService.Infrastructure.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePartnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.ProjectAssignment", b =>
                {
                    b.HasOne("AccessControlService.Infrastructure.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
