// <auto-generated />
using System;
using AccessControlService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControlService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    partial class AccessControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Label = "Fixture Dept: Headquarters"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Label = "Fixture Dept: Engineering",
                            ParentDepartmentId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Dept: Platform",
                            ParentDepartmentId = new Guid("11111111-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagesDepartmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ManagesDepartmentId")
                        .IsUnique();

                    b.ToTable("people", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Label = "Fixture Person: Executive",
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Label = "Fixture Person: Director",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000001"),
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Person: Platform Lead",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000002"),
                            ManagesDepartmentId = new Guid("11111111-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            DepartmentId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Label = "Fixture Person: Engineer",
                            ManagerId = new Guid("22222222-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Department", b =>
                {
                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AccessControlService.Infrastructure.Persistence.Person", b =>
                {
                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessControlService.Infrastructure.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AccessControlService.Infrastructure.Persistence.Department", null)
                        .WithMany()
                        .HasForeignKey("ManagesDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
