name: All services - build artifacts

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  node-services:
    strategy:
      fail-fast: false
      matrix:
        service_path:
          - services/frontend
          - services/bff
          - services/people-service
          - services/resourcing-service
          - services/integration-timetracker
          - services/integration-peopleforce
          - services/work-management-service
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service_path: ${{ matrix.service_path }}

  dotnet-services:
    strategy:
      fail-fast: false
      matrix:
        service_path:
          - services/authentication-service
          - services/access-control-service
    uses: ./.github/workflows/_reusable-dotnet-ci.yml
    with:
      service_path: ${{ matrix.service_path }}
