name: bff CI

on:
  push:
    paths:
      - 'services/bff/**'
      - '.github/workflows/bff-ci.yml'
      - '.github/workflows/_reusable-node-ci.yml'
  pull_request:
    paths:
      - 'services/bff/**'
      - '.github/workflows/bff-ci.yml'
      - '.github/workflows/_reusable-node-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/_reusable-node-ci.yml
    with:
      service_path: services/bff
